version: "3.9"

services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    image: react-personal-website:dev
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      NODE_ENV: development
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
    command: npm run start

  web-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    image: react-personal-website:latest
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      NODE_ENV: production
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
    command: npm run start
