version: "3.9"

services:
  web-dev:
    image: react-personal-website
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=development
    command: npm run start

  web-dev-prod:
    image: react-personal-website
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=production
    command: npm run start

  web-prod:
    build:
      context: .
      dockerfile: dockerfile.prod
    image: react-personal-website:prod
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=production
    command: node server/server.js
