version: "3.9"

services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    image: react-personal-website:dev
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NEXT_PUBLIC_BASE_URL: "https://www.miguelsietereales.com"
      NEXT_PUBLIC_FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
    command: npm run dev

  web-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    image: react-personal-website:latest
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      NEXT_PUBLIC_BASE_URL: "https://www.miguelsietereales.com"
      NEXT_PUBLIC_FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
    command: npm run start
